"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mbot_encoder_t(object):
    __slots__ = ["utime", "leftticks", "rightticks", "left_delta", "right_delta"]

    __typenames__ = ["int64_t", "int64_t", "int64_t", "int16_t", "int16_t"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.leftticks = 0
        self.rightticks = 0
        self.left_delta = 0
        self.right_delta = 0

    def encode(self):
        buf = BytesIO()
        buf.write(mbot_encoder_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqqhh", self.utime, self.leftticks, self.rightticks, self.left_delta, self.right_delta))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mbot_encoder_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mbot_encoder_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mbot_encoder_t()
        self.utime, self.leftticks, self.rightticks, self.left_delta, self.right_delta = struct.unpack(">qqqhh", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if mbot_encoder_t in parents: return 0
        tmphash = (0xd4582742ffd4e8e8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mbot_encoder_t._packed_fingerprint is None:
            mbot_encoder_t._packed_fingerprint = struct.pack(">Q", mbot_encoder_t._get_hash_recursive([]))
        return mbot_encoder_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", mbot_encoder_t._get_packed_fingerprint())[0]

