"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class occupancy_grid_t(object):
    __slots__ = ["utime", "origin_x", "origin_y", "meters_per_cell", "width", "height", "num_cells", "cells"]

    __typenames__ = ["int64_t", "float", "float", "float", "int32_t", "int32_t", "int32_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None, None, ["num_cells"]]

    def __init__(self):
        self.utime = 0
        self.origin_x = 0.0
        self.origin_y = 0.0
        self.meters_per_cell = 0.0
        self.width = 0
        self.height = 0
        self.num_cells = 0
        self.cells = []

    def encode(self):
        buf = BytesIO()
        buf.write(occupancy_grid_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfffiii", self.utime, self.origin_x, self.origin_y, self.meters_per_cell, self.width, self.height, self.num_cells))
        buf.write(struct.pack('>%db' % self.num_cells, *self.cells[:self.num_cells]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != occupancy_grid_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return occupancy_grid_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = occupancy_grid_t()
        self.utime, self.origin_x, self.origin_y, self.meters_per_cell, self.width, self.height, self.num_cells = struct.unpack(">qfffiii", buf.read(32))
        self.cells = struct.unpack('>%db' % self.num_cells, buf.read(self.num_cells))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if occupancy_grid_t in parents: return 0
        tmphash = (0x6aa23f24a5336649) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if occupancy_grid_t._packed_fingerprint is None:
            occupancy_grid_t._packed_fingerprint = struct.pack(">Q", occupancy_grid_t._get_hash_recursive([]))
        return occupancy_grid_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", occupancy_grid_t._get_packed_fingerprint())[0]

