"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class oled_message_t(object):
    __slots__ = ["utime", "line1", "line2"]

    __typenames__ = ["int64_t", "string", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.utime = 0
        self.line1 = ""
        self.line2 = ""

    def encode(self):
        buf = BytesIO()
        buf.write(oled_message_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __line1_encoded = self.line1.encode('utf-8')
        buf.write(struct.pack('>I', len(__line1_encoded)+1))
        buf.write(__line1_encoded)
        buf.write(b"\0")
        __line2_encoded = self.line2.encode('utf-8')
        buf.write(struct.pack('>I', len(__line2_encoded)+1))
        buf.write(__line2_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != oled_message_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return oled_message_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = oled_message_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __line1_len = struct.unpack('>I', buf.read(4))[0]
        self.line1 = buf.read(__line1_len)[:-1].decode('utf-8', 'replace')
        __line2_len = struct.unpack('>I', buf.read(4))[0]
        self.line2 = buf.read(__line2_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if oled_message_t in parents: return 0
        tmphash = (0xfcdfd38929ceee80) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if oled_message_t._packed_fingerprint is None:
            oled_message_t._packed_fingerprint = struct.pack(">Q", oled_message_t._get_hash_recursive([]))
        return oled_message_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", oled_message_t._get_packed_fingerprint())[0]

