"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class reset_odometry_t(object):
    __slots__ = ["x", "y", "theta"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.x = 0.0
        self.y = 0.0
        self.theta = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(reset_odometry_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.x, self.y, self.theta))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != reset_odometry_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return reset_odometry_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = reset_odometry_t()
        self.x, self.y, self.theta = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if reset_odometry_t in parents: return 0
        tmphash = (0xb3f79e70d04fabca) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if reset_odometry_t._packed_fingerprint is None:
            reset_odometry_t._packed_fingerprint = struct.pack(">Q", reset_odometry_t._get_hash_recursive([]))
        return reset_odometry_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", reset_odometry_t._get_packed_fingerprint())[0]

